<?php 

return [
	"models" => [
		"users" => 'App\Models\User',
		"menu" =>  'App\Models\Menu',
		"roles" =>  'App\Models\Role',
		"permissions" =>  'App\Models\Permission',
	],
	"seeds" => [
		"users" => UsersTableSeeder::class,
		"menu" => MenuTableSeeder::class
	],
	"themes" => [
		[
			"version" => "v1",
			"name" => "AdminLTE Admin Template",
			"description" => "Powered of Bootstrap framework",
			"images" => "v1.png",
			"status" => true
		],
		[
			"version" => "v2",
			"name" => "BULKIT Admin Template",
			"description" => "Powered of Bulma framework",
			"images" => "v2.png",
			"status" => false
		],
	],
	"localization" => [
		"id_ID" => "id", 
		"en_EN" => "en", 
	],
	"first_class" => "owner",
	"roles" => [
		"owner" => [
			"menu" => [
				"dashboard",
				"setting",
				"application",
				"menu",
				"users",
				"access control",
				"roles",
				"access",
				"permissions",
				"point of sales",
				"master",
				"departement",
				"brands",
				"products",
				"purchase",
				"sales",
				"report",
				"purchase report",
				"sales report",
				"user guide"
			],
			"permissions" => [
				"dashboard" => "i",
				"application" => "i,c,st",
				"users" => "i,c,sh,st,e,u,d",
				"menu" => "i,st,e,u",
				"roles" => "i,c,sh,st,e,u,d",
				"access" => "i,st",
				"permissions" => "i,st",
				"departement" => "i,c,sh,st,e,u,d",
				"brands" => "i,c,sh,st,e,u,d",
				"products" => "i,c,sh,st,e,u,d",
				"purchase" => "i,c,sh,st,e,u,d",
				"sales" => "i,c,st",
				"purchase report" => "i",
				"sales report" => "i",
				"user guide" => "i",
				"profile" => "i,st",
			]
		],
		"admin" => [
			"menu" => [
				"dashboard",
				"setting",
				"application",
				"menu",
				"users",
				"access control",
				"roles",
				"point of sales",
				"master",
				"departement",
				"brands",
				"products",
				"purchase",
				"sales",
				"user guide"
			],
			"permissions" => [
				"dashboard" => "i",
				"application" => "i,st",
				"users" => "i,c,sh,st,e,u,d",
				"menu" => "i,st",
				"roles" => "i,c,sh,st,e,u,d",
				"departement" => "i,c,sh,st,e,u,d",
				"brands" => "i,c,sh,st,e,u,d",
				"products" => "i,c,sh,st,e,u,d",
				"purchase" => "i,c,sh,st,e,u,d",
				"sales" => "i,c,st",
				"user guide" => "i",
				"profile" => "i,st",
			]
		],
		"casier" => [
			"menu" => [
				"dashboard",
				"setting",
				"application",
				"point of sales",
				"master",
				"departement",
				"brands",
				"products",
				"purchase",
				"sales",
				"user guide"
			],
			"permissions" => [
				"dashboard" => "i",
				"application" => "i",
				"departement" => "i,c,sh,st",
				"brands" => "i,c,sh,st",
				"products" => "i,c,sh,st",
				"purchase" => "i,c,sh,st",
				"sales" => "i,c,st",
				"user guide" => "i",
				"profile" => "i,st",
			]
		],
		"demo" => [
			"menu" => [
				"dashboard",
				"setting",
				"application",
				"menu",
				"users",
				"access control",
				"roles",
				"access",
				"permissions",
				"point of sales",
				"master",
				"departement",
				"brands",
				"products",
				"purchase",
				"sales",
				"report",
				"purchase report",
				"sales report",
				"user guide"
			],
			"permissions" => [
				"dashboard" => "i",
				"application" => "i",
				"users" => "i,c,sh,st",
				"menu" => "i,e",
				"roles" => "i,c,sh,st,e,u",
				"access" => "i",
				"permissions" => "i",
				"departement" => "i,c,sh,st,e,u,d",
				"brands" => "i,c,sh,st,e,u,d",
				"products" => "i,c,sh,st,e,u",
				"purchase" => "i,c,sh,st,e,u,d",
				"sales" => "i,c,st",
				"purchase report" => "i",
				"sales report" => "i",
				"user guide" => "i",
				"profile" => "i,st",
			]
		],
	],
	"permissions" => [
		// "dashboard",
		// "application",
		// "menu",
		// "sales",
		// "profile",
	],
	"permissions_maps" => [
		"i" => "index",
		"c" => "create",
		"sh" => "show",
		"st" => "store",
		"e" => "edit",
		"u" => "update",
		"d" => "destroy",
	],
];